BoozeBot_Archieved/Backend/forms.py
from flask_wtf import FlaskForm, Form
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, IntegerField, BooleanField, FileField, FormField, FieldList
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

#TODO: custom drink form, registration form implement, buy credits form implement

#filefield doesn't work
#class uploadMenu(Form):
#    name = StringField('Menu Name', validators=[DataRequired(), Length(min=2, max=30)])
#    menu = FileField('Menu', validators=[DataRequired(), FileAllowed(['ini'])])
#    ingredients = FileField('Ingredients', validators=[DataRequired(), FileAllowed(['ini'])])
#    pumps = FileField('Pumps', validators=[DataRequired(), FileAllowed(['ini'])])
#    confirm = BooleanField('Confirm Settings')
#    submit = SubmitField('Upload')

#custom drink
class ingredientSelect(FlaskForm):
    name = IntegerField()

class customDrink(FlaskForm):
    #A form for one or more addresses
    ingredients = FieldList(FormField(ingredientSelect), min_entries=1)
#custom drink

class uploadMenu(Form):
    name = StringField('Menu Name', validators=[DataRequired(), Length(min=2, max=30)])
    browse = FileField('Browse File system')
    location = StringField('Menu directory location', validators=[DataRequired(), Length(min=2)])
    confirm = BooleanField('Confirm Settings')
    submit = SubmitField('Upload')

class adminSettings(FlaskForm):
    openBar = BooleanField('Open Bar')
    custom = BooleanField('Custom Drinks')
    adminOveride = BooleanField('Free Drinks for Admin')
    confirm = BooleanField('Confirm Settings')
    submit = SubmitField('Continue')

class buyDrink(FlaskForm):
    ID = StringField('Student ID', validators=[DataRequired(), Length(min=2, max=30)])
    confirm = BooleanField('Confirm Order')
    submit = SubmitField('Continue')

class confirmOrder(FlaskForm):
    confirm = BooleanField('Confirm Order')
    submit = SubmitField('Continue')

class adminLogin(FlaskForm):
    ID = StringField('Student ID', validators=[DataRequired(), Length(min=2, max=30)])
    submit = SubmitField('Login')

class addCredits(FlaskForm):
    ID = StringField('Student ID', validators=[DataRequired(), Length(min=2, max=30)])
    adminID = StringField('Admin ID', validators=[DataRequired(), Length(min=2, max=30)])
    credit = IntegerField('Credit', validators=[DataRequired()])
    submit = SubmitField('Add Credits')

class newUser(FlaskForm):
    ID = StringField('Student ID', validators=[DataRequired(), Length(min=2, max=30)])
    name = StringField('Name', validators=[DataRequired(), Length(min=2, max=30)])
    adminID = StringField('Admin ID', validators=[DataRequired(), Length(min=2, max=30)])
    credit = IntegerField('Credit', validators=[DataRequired()])
    submit = SubmitField('Add Credits')

BoozeBot_Archieved/Backend/views/menu.py
import functools
import Data

from flask import Blueprint, render_template, session

bp = Blueprint('menu', __name__, url_prefix='/menu')


@bp.route('/')
def menu():
    return render_template('menu.html', menu=Data.menu, title='Menu')


@bp.route("/<drinkName>", methods=['GET', 'POST'])
def drink(drinkName):
    drinkExists = False
    if session['OpenBar'] == True:
        form = confirmOrder()
    else:
        drink_dict = {
            "drink_name": drinkName
        }
        return render_template('card-order.html', drink_dict=drink_dict)

    #
    # if form.confirm.data:
    #     is_drunk = Database.is_drunk(form.ID.data)
    #
    #     for drink in Data.menu:
    #         if Data.menu[drink].name == drinkName:
    #
    #             if is_drunk and Data.menu[drink].getStndDrink() != 0.0:
    #                 return redirect(url_for('drunk'))
    #
    #             drinkExists = True
    #             if session['OpenBar'] == True:
    #                 submitDrink(-1, drink)
    #             else:
    #                 purchaseDrink(form.ID.data, drink)
    #             return redirect(url_for('menu'))
    # for drink in Data.menu:
    #     if Data.menu[drink].name == drinkName:
    #         drinkExists = True
    #         return render_template('confirm.html', drink=Data.menu[drink], form=form)
    # if drinkExists == False:
    #     return redirect(url_for('drinkMissing'))
    # return render_template('menu.html', menu=Data.menu)

BoozeBot_Archieved/Backend/templates/card-order.html
{% extends "layout.html" %}
{% block content %}
  <h2 class="page-heading">LOGIN</h2>
<script>
window.location.replace("/card_order_drink/{{ drink_dict.drink_name }}");
</script>


    <p>
        Please scan your student card
    </p>
{% endblock content %}

BoozeBot_Archieved/Backend/templates/confirm.html
{% extends "layout.html" %}
{% block content %}
  <h2 class="page-heading">{{ drink.name }}</h2>
  {% if session['OpenBar'] == False %}
    <form method="POST" action="">
      <option>
        {{ form.ID.label }}
        {{ form.ID(class_="input-text") }}
      </option>

      <option class="check-container">
        {{ form.confirm(class_="check-box confirm") }}
        <span class="checkmark"></span>
        {{ form.confirm.label }}
      </option>

      {{ form.submit(class_="button submit") }}
    </form>

  {% else %}
  <form method="POST" action="">
    <option class="check-container">
      {{ form.confirm(class_="check-box confirm") }}
      <span class="checkmark"></span>
      {{ form.confirm.label }}
    </option>

    {{ form.submit(class_="button submit") }}
  </form>
  {% endif %}
{% endblock content %}

BoozeBot_Archieved/Backend/templates/credits.html
{% extends "layout.html" %}
{% block content %}
  <h2 class="page-heading">PURCHASE CREDITS</h2>

  <form method="POST" action="">
    <option>
      {{ form.ID.label }}
      {{ form.ID(class_="input-text") }}
    </option>

    <option>
      {{ form.adminID.label }}
      {{ form.adminID(class_="input-text") }}
    </option>

    <option>
      {{ form.credit.label }}
      {{ form.credit(class_="input-text") }}
    </option>

    {{ form.submit(class_="button submit") }}
  </form>
{% endblock content %}

BoozeBot_Archieved/Backend/templates/custom.html
{% extends "layout.html" %}
{% block content %}
  {% for ingredient in form.ingredients %}
    {{ ingredient.hidden_tag() }}
  {% endfor %}
{% endblock content %}

BoozeBot_Archieved/Backend/templates/drunk.html
{% extends "layout.html" %}
{% block content %}
<script>
    setTimeout(function () {
   window.location.href = "/menu"; //will redirect to your blog page (an ex: blog.html)
}, 3000); // Go to menu after 3 seconds
</script>
  <h2 class="page-heading">No Booze for You!</h2>
    <p>
        Come back 1 hour.
    </p>
{% endblock content %}

BoozeBot_Archieved/Backend/templates/home.html
{% extends "layout.html" %}
{% block content %}

{% endblock content %}

BoozeBot_Archieved/Backend/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='Themes/Standard.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
    {% if title %}
      <title>BoozeBot - {{ title }}</title>
    {% else %}
      <title>BoozeBot</title>
    {% endif %}
  </head>



  <body>

    <header>
      <nav class="menu site-menu">
        <h1 id="site-heading"><a href="{{ url_for('home') }}">BoozeBot</a></h1>
        <menu>
          <ul>
            <a href="{{ url_for('home') }}"><li id="Setup">Setup</li></a>
            <a href="{{ url_for('menu.menu') }}"><li id="Menu">Menu</li></a>
            {% if  session['Auth'] %}
              {% if session['Auth'] == True %}
                  <a href="{{ url_for('setting') }}"><li id="Settings">Settings</li></a>
                  <a href="{{ url_for('logout') }}"><li id="Logout">Logout</li></a>
              {% else %}
                  <a href="{{ url_for('register') }}"><li id="Register">Register</li></a>
                  <a href="{{ url_for('buyCredit') }}"><li id="Buy-Credits">Credits</li></a>
                  <a href="{{ url_for('login') }}"><li id="Admin">Admin</li></a>
              {% endif %}
            {% else %}
                <a href="{{ url_for('register') }}"><li id="Register">Register</li></a>
                <a href="{{ url_for('buyCredit') }}"><li id="Buy-Credits">Credits</li></a>
                <a href="{{ url_for('login') }}"><li id="Admin">Admin</li></a>
            {% endif %}
          </ul>
        </menu>
      </nav>
    </header>

    <section id="popup-messages">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="popup-text">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </section>

    <main>
      <article>
        {% block content %}{% endblock %}
      </article>
    </main>

    <footer>

    </footer>
  </body>
</html>

BoozeBot_Archieved/Backend/templates/login.html
{% extends "layout.html" %}
{% block content %}
  <h2 class="page-heading">LOGIN</h2>
<script>
window.location.replace("/card_login");
// setTimeout(function () {
//    window.location.href = "/card_login"; //will redirect to your blog page (an ex: blog.html)
// }, 500); //will call the function after 2 secs.

</script>
    <p>
        Please scan your student card
    </p>
{% endblock content %}

BoozeBot_Archieved/Backend/templates/menu.html
{% extends "layout.html" %}
{% block content %}
  <h2 class="page-heading">MENU</h2>
  <ul class="menu drinks-menu">
    {% if session['CustomDrinks'] == True %}
      <a href=""><li class="menu-item Custom">Custom<small> - this feature is yet to be implemented</small></li></a>
    {% endif %}
    {% for drink in menu %}
      <a href="/menu/{{ menu[drink].name }}"><li class="menu-item {{ menu[drink].name }}">{{ menu[drink].name }}</li></a>
    {% endfor %}
  </ul>
{% endblock content %}

BoozeBot_Archieved/Backend/templates/register.html
{% extends "layout.html" %}
{% block content %}
  <h2 class="page-heading">REGISTER</h2>

  <form method="POST" action="">
    <option>
      {{ form.ID.label }}
      {{ form.ID(class_="input-text") }}
    </option>

    <option>
      {{ form.name.label }}
      {{ form.name(class_="input-text") }}
    </option>

    <option>
      {{ form.adminID.label }}
      {{ form.adminID(class_="input-text") }}
    </option>

    <option>
      {{ form.credit.label }}
      {{ form.credit(class_="input-text") }}
    </option>

    {{ form.submit(class_="button submit") }}
  </form>
{% endblock content %}

BoozeBot_Archieved/Backend/templates/select-menu.html
{% extends "settings-layout.html" %}
{% block settings %}
  <h2 class="page-heading">MENU-MENU</h2>
  <ul class="menu menu-menu">
  {% for menu in list %}
    <a href="/select/menu/{{ menu }}"><li class="menu-item">{{ menu }}</li></a>
  {% endfor %}
  </ul>
{% endblock settings %}

BoozeBot_Archieved/Backend/templates/settings-layout.html
{% extends "layout.html" %}
{% block content %}
  {% if session['Auth'] %}
    {% if session['Auth'] == True %}
      <nav class="menu settings-menu">
        <ul>
          <a href="{{ url_for('newMenu') }}"><li class="nav-item">Upload Menu</li></a>
          <a href="{{ url_for('selectMenu') }}"><li class="nav-item">Select Menu</li></a>
          <a href="{{ url_for('setting') }}"><li class="nav-item">Settings</li></a>
        </ul>
      </nav>
      {% block settings %}{% endblock %}
    {% else %}
      <h2 class="page-heading">Access Denied!</h2>
      <p>You need to be logged in as admin to access this page</p>
      <a href="{{ url_for('menu.menu') }}">Return to Menu</a>
      <img src="/templates/Themes/Theme-Images/loading.gif">
    {% endif %}
  {% else %}
    <p>You need to be logged in as admin to access this page</p>
    <a href="{{ url_for('menu.menu') }}">Return to Menu</a>
  {% endif %}
{% endblock content %}

BoozeBot_Archieved/Backend/templates/timeout.html
{% extends "layout.html" %}
{% block content %}
  <h2 class="page-heading">LOGIN</h2>
  {% if session['Auth'] %}
    {% if session['Auth'] == True %}
      <p>Already Logged In</p>
    {% else %}
    <form method="POST" action="" id="login-form">
      <option>
        {{ form.ID.label }}
        {{ form.ID(class_="input-text") }}
      </option>

      {{ form.submit(class_="button submit") }}
    </form>
    {% endif %}

  {% else %}
  <form method="POST" action="" id="login-form">
    <option>
      {{ form.ID.label }}
      {{ form.ID(class_="input-text") }}
    </option>

    {{ form.submit(class_="button submit") }}
  </form>
  {% endif %}
{% endblock content %}

BoozeBot_Archieved/Backend/templates/upload-menu.html
{% extends "settings-layout.html" %}
{% block settings %}
<h2 class="page-heading">UPLOAD</h2>

<form method="POST" action="">
  <option>
    {{ form.name.label(class_="input-text") }}
    {{ form.name }}
  </option>

  <option>
    {{ form.browse.label }}
    {{ form.browse(class_="button browse") }}
  </option>

  <option>
    {{ form.location.label }}
    {{ form.location(class_="input-text") }}
  </option>

  <option class="check-container">
    {{ form.confirm(class_="check-box confirm") }}
    <span class="checkmark"></span>
    {{ form.confirm.label }}
  </option>

  {{ form.submit(class_="button submit") }}
</form>
  </form>
{% endblock settings %}